services:
  compliance-db:
    image: mysql:8.0
    container_name: compliance-hub-db
    restart: always
    privileged: true
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  compliance-app:
    build: .
    container_name: compliance-hub-app
    restart: always
    ports:
      - "9002:3000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=compliance-db
    depends_on:
      - compliance-db


volumes:
  mysql_data:
